version: '3'
services:
  angular-app:
    build:
      context: ./front
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app
      - /app/node_modules
    command: npm start

  backend:
    build:
      context: ./back
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

  db:
    build:
      context: ./db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql